package com.moneymatters.core.theme

import androidx.compose.ui.graphics.Color

// Sunrise (Light Mode)
val SunriseBgBase = Color(0xFFFFFBF5)
val SunriseBgGradientBottom = Color(0xFFFFF3E8)
val SunriseBgElevated = Color(0xFFFFFFFF)
val SunriseBgSunk = Color(0xFFF5EFE6)
val SunriseTextPrimary = Color(0xFF1A1814)
val SunriseTextSecondary = Color(0xFF6B6457)
val SunriseTextMuted = Color(0xFF9F968A)
val SunriseAccentPrimary = Color(0xFFFF6B35)
val SunriseAccentSoft = Color(0xFFFFE4D6)
val SunriseSuccess = Color(0xFF2D8B5F)
val SunriseSuccessSoft = Color(0xFFD4EDD9)
val SunriseDanger = Color(0xFFD63B3B)
val SunriseDangerSoft = Color(0xFFFDE2E2)
val SunriseInfo = Color(0xFF2E5AAC)
val SunriseInfoSoft = Color(0xFFDCE7FA)
val SunriseStreak = Color(0xFFFF8C42)
val SunriseGold = Color(0xFFF4B740)

// Midnight (Dark Mode)
val MidnightBgBase = Color(0xFF15110D)
val MidnightBgElevated = Color(0xFF1F1A14)
val MidnightBgSunk = Color(0xFF0F0B08)
val MidnightTextPrimary = Color(0xFFFAF4EA)
val MidnightTextSecondary = Color(0xFFB8AFA3)
val MidnightTextMuted = Color(0xFF7A7168)
val MidnightAccentPrimary = Color(0xFFFF8856)
val MidnightAccentSoft = Color(0xFF3A2418)
val MidnightSuccess = Color(0xFF4FAE7B)
val MidnightSuccessSoft = Color(0xFF1A2E22)
val MidnightDanger = Color(0xFFE85A5A)
val MidnightDangerSoft = Color(0xFF3A1A1A)
val MidnightInfo = Color(0xFF5B7CC9)
val MidnightInfoSoft = Color(0xFF1A2438)
val MidnightStreak = Color(0xFFFFA45C)
val MidnightGold = Color(0xFFFFCB57)
